### ISSUE TITLE
[5.0.5 build 329] Array Tooltips not localized

### ISSUE THREAD

**Issue by The-Fireplace** [progwml6/compactsolars#14]
![image](https://cloud.githubusercontent.com/assets/5914284/21201468/b2f22e58-c210-11e6-9e79-e74f3436a409.png)
Tested with all three arrays, and none of them have their tooltips localized. All three show:
tile.compactsolars:powertier.tooltip

**Comment by SnowShock35** [comment]
@progwml6 @alexbegt If/When either of you get a chance, could you look into this one? Thanks 🙂

**Comment by alexbegt** [comment]
Lol Silly me, I pushed the code, but didn't push the language file... lol

**Comment by SnowShock35** [comment]
Is that why localisation and textures broke by any chance? 😜

**Comment by alexbegt** [comment]
Texture being broken might be due to IC2 renaming the solar generator texture for GUIs :P

**Comment by SnowShock35** [comment]
Ah I see! Bad them :P

**Comment by alexbegt** [comment]
Fixed!
