### ISSUE TITLE
[1.12.2] Solar show the sun icon during nightime

### ISSUE THREAD

**Issue by SnowShock35** [progwml6/compactsolars#21]
Hi Prog,

Just one quick thing, with compact solars - could be intentional - not sure. The little sun icon lights up even during the night time. (No power is outputted - just visual).

#### Issue details

- Minecraft 1.12.2
- Minecraft Forge 14.23.0.2529
- Compact Solars 5.0.15 build 338

#### Issue media

![Issue media #1](https://ss.blamesnow.co.uk/2017/11/1509899417-f01a9ca5.png)

**Comment by alexbegt** [comment]
Fixed with https://github.com/progwml6/compactsolars/commit/d9ac7be8e5234b168c6e4d62e3c7d46b1fa5576c
