### ISSUE TITLE
Jar File?

### ISSUE THREAD

**Issue by carTloyal123** [progwml6/compactsolars#9]
I was extremely excited to find any update to this mod since 1.10 came onto the modding scene but I am unfortunately not savvy with coding. I would love to either have some simple guidance for creating the jar file myself or perhaps a download link for a working jar. Any help is greatly appreciated.
Thanks!

**Comment by alexbegt** [comment]
There is now a 1.10 and a 1.10.2 version of Compact Solars on curse (http://minecraft.curseforge.com/projects/compact-solars), It uses the IC2 builds for 1.10!
